from enum import StrEnum

class MarkerType(StrEnum):
    OPEN_LONG = "OPEN_LONG"
    OPEN_SHORT = "OPEN_SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    FORCE_CLOSE = "FORCE_CLOSE"
    RISK_REJECTED = "RISK_REJECTED"
    FUNDING_FEE = "FUNDING_FEE"
