from enum import StrEnum

class ReplayEventType(StrEnum):
    KLINE = "KLINE"
    SIGNAL = "SIGNAL"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELED = "ORDER_CANCELED"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    RISK_TRIGGERED = "RISK_TRIGGERED"
    POSITION_UPDATED = "POSITION_UPDATED"
    EQUITY_UPDATED = "EQUITY_UPDATED"
    DRAWDOWN_UPDATED = "DRAWDOWN_UPDATED"
    COST_CHARGED = "COST_CHARGED"
    FUNDING_FEE_CHARGED = "FUNDING_FEE_CHARGED"
    STRATEGY_PAUSED = "STRATEGY_PAUSED"
