from dataclasses import dataclass
import os

@dataclass(frozen=True)
class Settings:
    service_name: str = os.getenv("SERVICE_NAME", "api-gateway")
    env: str = os.getenv("ENV", "dev")
    auth_service_url: str = os.getenv("AUTH_SERVICE_URL", "http://localhost:8001")
    strategy_service_url: str = os.getenv("STRATEGY_SERVICE_URL", "http://localhost:8002")
    market_data_service_url: str = os.getenv("MARKET_DATA_SERVICE_URL", "http://localhost:8003")
    backtest_service_url: str = os.getenv("BACKTEST_SERVICE_URL", "http://localhost:8004")
    replay_service_url: str = os.getenv("REPLAY_SERVICE_URL", "http://localhost:8005")
    ai_analysis_service_url: str = os.getenv("AI_ANALYSIS_SERVICE_URL", "http://localhost:8006")
    strategy_score_service_url: str = os.getenv("STRATEGY_SCORE_SERVICE_URL", "http://localhost:8007")
    report_service_url: str = os.getenv("REPORT_SERVICE_URL", "http://localhost:8008")
    realtime_state_service_url: str = os.getenv("REALTIME_STATE_SERVICE_URL", "http://localhost:8012")
    signal_engine_url: str = os.getenv("SIGNAL_ENGINE_URL", "http://localhost:8009")
    risk_engine_url: str = os.getenv("RISK_ENGINE_URL", "http://localhost:8013")
    paper_trading_service_url: str = os.getenv("PAPER_TRADING_SERVICE_URL", "http://localhost:8014")
    paper_monitor_service_url: str = os.getenv("PAPER_MONITOR_SERVICE_URL", "http://localhost:8015")
    exchange_account_service_url: str = os.getenv("EXCHANGE_ACCOUNT_SERVICE_URL", "http://localhost:8016")
    order_executor_service_url: str = os.getenv("ORDER_EXECUTOR_SERVICE_URL", "http://localhost:8018")
    live_risk_guard_service_url: str = os.getenv("LIVE_RISK_GUARD_SERVICE_URL", "http://localhost:8019")
    live_trading_monitor_service_url: str = os.getenv("LIVE_TRADING_MONITOR_SERVICE_URL", "http://localhost:8020")
    live_monitor_service_url: str = os.getenv("LIVE_MONITOR_SERVICE_URL", os.getenv("LIVE_TRADING_MONITOR_SERVICE_URL", "http://localhost:8020"))
    alert_center_service_url: str = os.getenv("ALERT_CENTER_SERVICE_URL", "http://localhost:8021")
    audit_center_service_url: str = os.getenv("AUDIT_CENTER_SERVICE_URL", "http://localhost:8022")
    strategy_lifecycle_center_url: str = os.getenv("STRATEGY_LIFECYCLE_CENTER_URL", "http://localhost:8023")
    redis_url: str = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    jwt_secret: str = os.getenv("JWT_SECRET", "change_me")
    log_level: str = os.getenv("LOG_LEVEL", "INFO")

settings = Settings()
