from enum import StrEnum
class LedgerType(StrEnum):
    OPEN_MARGIN_LOCK = "OPEN_MARGIN_LOCK"
    RELEASE_MARGIN = "RELEASE_MARGIN"
    TRADE_FEE = "TRADE_FEE"
    REALIZED_PNL = "REALIZED_PNL"
    FUNDING_FEE_PAY = "FUNDING_FEE_PAY"
    FUNDING_FEE_RECEIVE = "FUNDING_FEE_RECEIVE"
