from enum import StrEnum
class AdmissionDecision(StrEnum):
    REJECT = "REJECT"
    RETEST_REQUIRED = "RETEST_REQUIRED"
    ALLOW_SIMULATION = "ALLOW_SIMULATION"
    ALLOW_SMALL_LIVE_AFTER_SIMULATION = "ALLOW_SMALL_LIVE_AFTER_SIMULATION"
    ALLOW_LIVE = "ALLOW_LIVE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
