from datetime import datetime
from uuid import uuid4
from sqlalchemy import Boolean, DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.infrastructure.postgres.base import Base
class AlertEventModel(Base):
    __tablename__="alert_event"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); fingerprint:Mapped[str]=mapped_column(String(128),index=True); source:Mapped[str]=mapped_column(String(64),index=True); level:Mapped[str]=mapped_column(String(32),index=True); status:Mapped[str]=mapped_column(String(64),index=True); title:Mapped[str]=mapped_column(String(256)); message:Mapped[str]=mapped_column(Text); rule_code:Mapped[str|None]=mapped_column(String(128),nullable=True); resource_type:Mapped[str|None]=mapped_column(String(64),nullable=True); resource_id:Mapped[str|None]=mapped_column(String(128),nullable=True); occurrence_count:Mapped[int]=mapped_column(default=1); payload_json:Mapped[dict|None]=mapped_column(JSONB,nullable=True); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); first_occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); last_occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class AlertRuleModel(Base):
    __tablename__="alert_rule"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); rule_code:Mapped[str]=mapped_column(String(128),unique=True); rule_name:Mapped[str]=mapped_column(String(128)); source:Mapped[str]=mapped_column(String(64)); enabled:Mapped[bool]=mapped_column(Boolean,default=True); level:Mapped[str]=mapped_column(String(32)); notification_channels:Mapped[list]=mapped_column(JSONB); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class AlertNotificationModel(Base):
    __tablename__="alert_notification"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); alert_event_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); channel:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class AlertAcknowledgementModel(Base):
    __tablename__="alert_acknowledgement"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); alert_event_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); acknowledged_by:Mapped[str]=mapped_column(UUID(as_uuid=False)); note:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class AlertSuppressionModel(Base):
    __tablename__="alert_suppression"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); source:Mapped[str|None]=mapped_column(String(64)); rule_code:Mapped[str|None]=mapped_column(String(128)); reason:Mapped[str]=mapped_column(Text); enabled:Mapped[bool]=mapped_column(Boolean,default=True); start_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); end_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
