from datetime import date, datetime
from uuid import uuid4
from sqlalchemy import Date, DateTime, Numeric, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.infrastructure.postgres.base import Base
class PaperEquityCurveModel(Base):
    __tablename__="paper_equity_curve"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); strategy_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True,index=True); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str|None]=mapped_column(String(64),nullable=True); ts:Mapped[datetime]=mapped_column(DateTime(timezone=True)); equity:Mapped[float]=mapped_column(Numeric(32,8)); available_balance:Mapped[float]=mapped_column(Numeric(32,8)); margin_used:Mapped[float]=mapped_column(Numeric(32,8)); realized_pnl:Mapped[float]=mapped_column(Numeric(32,8)); unrealized_pnl:Mapped[float]=mapped_column(Numeric(32,8)); drawdown_pct:Mapped[float|None]=mapped_column(Numeric(18,8),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class PaperStrategyDailySummaryModel(Base):
    __tablename__="paper_strategy_daily_summary"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); trade_date:Mapped[date]=mapped_column(Date,index=True); exchange:Mapped[str]=mapped_column(String(32)); starting_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); ending_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); daily_return:Mapped[float|None]=mapped_column(Numeric(18,8)); realized_pnl:Mapped[float|None]=mapped_column(Numeric(32,8)); unrealized_pnl:Mapped[float|None]=mapped_column(Numeric(32,8)); max_drawdown:Mapped[float|None]=mapped_column(Numeric(18,8)); trade_count:Mapped[int]=mapped_column(default=0); win_trade_count:Mapped[int]=mapped_column(default=0); loss_trade_count:Mapped[int]=mapped_column(default=0); win_rate:Mapped[float|None]=mapped_column(Numeric(18,8)); fee_total:Mapped[float]=mapped_column(Numeric(32,8),default=0); slippage_total:Mapped[float]=mapped_column(Numeric(32,8),default=0); funding_fee_total:Mapped[float]=mapped_column(Numeric(32,8),default=0); cost_to_profit_ratio:Mapped[float|None]=mapped_column(Numeric(18,8)); risk_reject_count:Mapped[int]=mapped_column(default=0); reduce_only_count:Mapped[int]=mapped_column(default=0); pause_strategy_count:Mapped[int]=mapped_column(default=0); order_error_count:Mapped[int]=mapped_column(default=0); data_stale_count:Mapped[int]=mapped_column(default=0); summary_json:Mapped[dict|None]=mapped_column(JSONB,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class PaperRiskEventSummaryModel(Base):
    __tablename__="paper_risk_event_summary"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); trade_date:Mapped[date]=mapped_column(Date); risk_reject_count:Mapped[int]=mapped_column(default=0); market_stale_count:Mapped[int]=mapped_column(default=0); high_spread_count:Mapped[int]=mapped_column(default=0); high_funding_count:Mapped[int]=mapped_column(default=0); leverage_reject_count:Mapped[int]=mapped_column(default=0); position_size_reject_count:Mapped[int]=mapped_column(default=0); consecutive_loss_pause_count:Mapped[int]=mapped_column(default=0); daily_loss_reject_count:Mapped[int]=mapped_column(default=0); detail_json:Mapped[dict|None]=mapped_column(JSONB,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class SimulationObservationModel(Base):
    __tablename__="simulation_observation"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); symbols:Mapped[list]=mapped_column(JSONB); start_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); end_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); min_observation_days:Mapped[int]=mapped_column(default=7); status:Mapped[str]=mapped_column(String(64),index=True); latest_admission_result_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_by:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class SimulationAdmissionResultModel(Base):
    __tablename__="simulation_admission_result"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); observation_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); decision:Mapped[str]=mapped_column(String(64),index=True); passed:Mapped[bool]=mapped_column(default=False); score:Mapped[float|None]=mapped_column(Numeric(8,2)); observation_days:Mapped[int]=mapped_column(); trade_count:Mapped[int]=mapped_column(); total_return:Mapped[float|None]=mapped_column(Numeric(18,8)); max_drawdown:Mapped[float|None]=mapped_column(Numeric(18,8)); win_rate:Mapped[float|None]=mapped_column(Numeric(18,8)); profit_factor:Mapped[float|None]=mapped_column(Numeric(18,8)); max_consecutive_losses:Mapped[int|None]=mapped_column(); fee_total:Mapped[float|None]=mapped_column(Numeric(32,8)); slippage_total:Mapped[float|None]=mapped_column(Numeric(32,8)); funding_fee_total:Mapped[float|None]=mapped_column(Numeric(32,8)); cost_to_profit_ratio:Mapped[float|None]=mapped_column(Numeric(18,8)); risk_reject_count:Mapped[int|None]=mapped_column(); pause_strategy_count:Mapped[int|None]=mapped_column(); order_error_count:Mapped[int|None]=mapped_column(); data_stale_count:Mapped[int|None]=mapped_column(); reject_reasons:Mapped[list|None]=mapped_column(JSONB,nullable=True); warnings:Mapped[list|None]=mapped_column(JSONB,nullable=True); suggestions:Mapped[list|None]=mapped_column(JSONB,nullable=True); detail_json:Mapped[dict|None]=mapped_column(JSONB,nullable=True); approval_required:Mapped[bool]=mapped_column(default=True); approval_status:Mapped[str|None]=mapped_column(String(64),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class SimulationDailyReportModel(Base):
    __tablename__="simulation_daily_report"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True,index=True); report_date:Mapped[date]=mapped_column(Date,index=True); report_type:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(64)); report_json:Mapped[dict|None]=mapped_column(JSONB,nullable=True); html_object_key:Mapped[str|None]=mapped_column(String(512),nullable=True); json_object_key:Mapped[str|None]=mapped_column(String(512),nullable=True); error_message:Mapped[str|None]=mapped_column(String,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
