import os
from decimal import Decimal
class Settings:
    service_name = os.getenv("SERVICE_NAME", "live-trading-monitor-service")
    env = os.getenv("ENV", "dev")
    http_port = int(os.getenv("HTTP_PORT", "8020"))
    database_url = os.getenv("DATABASE_URL", "postgresql+asyncpg://astra:astra_password@localhost:5432/astraquant")
    redis_url = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    nats_url = os.getenv("NATS_URL", "nats://localhost:4222")
    exchange_account_service_url = os.getenv("EXCHANGE_ACCOUNT_SERVICE_URL", "http://localhost:8016")
    order_executor_service_url = os.getenv("ORDER_EXECUTOR_SERVICE_URL", "http://localhost:8018")
    live_risk_guard_service_url = os.getenv("LIVE_RISK_GUARD_SERVICE_URL", "http://localhost:8019")
    paper_monitor_service_url = os.getenv("PAPER_MONITOR_SERVICE_URL", "http://localhost:8015")
    strategy_service_url = os.getenv("STRATEGY_SERVICE_URL", "http://localhost:8002")
    report_service_url = os.getenv("REPORT_SERVICE_URL", "http://localhost:8008")
    min_live_observation_days = int(os.getenv("DEFAULT_MIN_LIVE_OBSERVATION_DAYS", "7"))
    min_live_trade_count = int(os.getenv("DEFAULT_MIN_LIVE_TRADE_COUNT", "10"))
    max_live_drawdown_pct = Decimal(os.getenv("DEFAULT_MAX_LIVE_DRAWDOWN_PCT", "0.03"))
    max_live_daily_loss_pct = Decimal(os.getenv("DEFAULT_MAX_LIVE_DAILY_LOSS_PCT", "0.01"))
    max_order_unknown_count = int(os.getenv("DEFAULT_MAX_ORDER_UNKNOWN_COUNT", "0"))
    max_circuit_breaker_count = int(os.getenv("DEFAULT_MAX_CIRCUIT_BREAKER_COUNT", "1"))
    max_cost_to_profit_ratio = Decimal(os.getenv("DEFAULT_MAX_COST_TO_PROFIT_RATIO", "0.25"))
    max_paper_live_deviation = Decimal(os.getenv("DEFAULT_MAX_PAPER_LIVE_DEVIATION", "0.50"))
    log_level = os.getenv("LOG_LEVEL", "INFO")
settings = Settings()
