from enum import StrEnum
class SignalStatus(StrEnum):
    GENERATED = "GENERATED"
    DEDUP_REJECTED = "DEDUP_REJECTED"
    PRECHECK_REJECTED = "PRECHECK_REJECTED"
    PUBLISHED = "PUBLISHED"
    RISK_CHECKING = "RISK_CHECKING"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_APPROVED = "RISK_APPROVED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_FAILED = "ORDER_FAILED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"
