from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_signal_schema"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table("signal_event", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("strategy_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("internal_symbol",sa.String(64),nullable=False), sa.Column("signal_type",sa.String(64),nullable=False), sa.Column("side",sa.String(16)), sa.Column("position_side",sa.String(16)), sa.Column("action",sa.String(32),nullable=False), sa.Column("confidence",sa.Numeric(8,4)), sa.Column("reference_price",sa.Numeric(32,16)), sa.Column("suggested_price",sa.Numeric(32,16)), sa.Column("suggested_size",sa.Numeric(32,16)), sa.Column("suggested_position_pct",sa.Numeric(18,8)), sa.Column("leverage",sa.Numeric(8,2)), sa.Column("reason",sa.Text()), sa.Column("indicator_snapshot",postgresql.JSONB), sa.Column("market_snapshot",postgresql.JSONB), sa.Column("freshness_snapshot",postgresql.JSONB), sa.Column("risk_hint_json",postgresql.JSONB), sa.Column("status",sa.String(64),nullable=False), sa.Column("dedup_key",sa.String(256)), sa.Column("bar_id",sa.String(128)), sa.Column("trace_id",sa.String(128)), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("idx_signal_event_strategy","signal_event",["strategy_id","strategy_version_id"]); op.create_index("idx_signal_event_symbol","signal_event",["exchange","internal_symbol"]); op.create_index("idx_signal_event_status","signal_event",["status"]); op.create_index("idx_signal_event_created_at","signal_event",["created_at"]); op.create_index("idx_signal_event_dedup_key","signal_event",["dedup_key"])
    op.create_table("strategy_runtime_state", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("strategy_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("internal_symbol",sa.String(64),nullable=False), sa.Column("runtime_status",sa.String(64),nullable=False), sa.Column("last_signal_id",postgresql.UUID(as_uuid=True)), sa.Column("last_signal_time",sa.DateTime(timezone=True)), sa.Column("last_bar_id",sa.String(128)), sa.Column("last_error_message",sa.Text()), sa.Column("runtime_config",postgresql.JSONB), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("uk_strategy_runtime_state","strategy_runtime_state",["strategy_version_id","exchange","internal_symbol"],unique=True); op.create_index("idx_strategy_runtime_status","strategy_runtime_state",["runtime_status"])
def downgrade():
    op.drop_table("strategy_runtime_state"); op.drop_table("signal_event")
