from enum import StrEnum
class AdmissionDecision(StrEnum):
    CONTINUE_OBSERVATION = "CONTINUE_OBSERVATION"
    RETEST_REQUIRED = "RETEST_REQUIRED"
    PAUSE_STRATEGY = "PAUSE_STRATEGY"
    ALLOW_SMALL_LIVE_APPLICATION = "ALLOW_SMALL_LIVE_APPLICATION"
    REJECT_SMALL_LIVE = "REJECT_SMALL_LIVE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
