from fastapi import APIRouter, Request
from app.clients.live_monitor_client import LiveMonitorClient
from app.middleware.permissions import require_permission
router=APIRouter(tags=["live-monitor"])
def read(request): require_permission(request,"live_monitor:read")
def manage(request): require_permission(request,"live_monitor:manage")
@router.get("/api/live-monitor/dashboard/overview")
async def overview(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/dashboard/overview",request,params=dict(request.query_params))
@router.get("/api/live-monitor/accounts/{account_id}/summary")
async def account(account_id: str, request: Request): read(request); return await LiveMonitorClient().request("GET",f"/live-monitor/accounts/{account_id}/summary",request)
@router.get("/api/live-monitor/strategies/{strategy_version_id}/summary")
async def strategy(strategy_version_id: str, request: Request): read(request); return await LiveMonitorClient().request("GET",f"/live-monitor/strategies/{strategy_version_id}/summary",request)
@router.get("/api/live-monitor/positions")
async def positions(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/positions",request,params=dict(request.query_params))
@router.get("/api/live-monitor/orders")
async def orders(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/orders",request,params=dict(request.query_params))
@router.get("/api/live-monitor/trades")
async def trades(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/trades",request,params=dict(request.query_params))
@router.get("/api/live-monitor/equity-curve")
async def equity(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/equity-curve",request,params=dict(request.query_params))
@router.get("/api/live-monitor/risk-events")
async def risk_events(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/risk-events",request,params=dict(request.query_params))
@router.post("/api/live-monitor/observations")
async def create_observation(payload: dict, request: Request): manage(request); return await LiveMonitorClient().request("POST","/live-monitor/observations",request,payload)
@router.post("/api/live-monitor/observations/{observation_id}/admission/calculate")
async def admission(observation_id: str, request: Request): manage(request); return await LiveMonitorClient().request("POST",f"/live-monitor/observations/{observation_id}/admission/calculate",request)
@router.get("/api/live-monitor/admission-results/{result_id}")
async def admission_result(result_id: str, request: Request): read(request); return await LiveMonitorClient().request("GET",f"/live-monitor/admission-results/{result_id}",request)
@router.get("/api/live-monitor/comparisons/paper-live")
async def comparison(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/comparisons/paper-live",request,params=dict(request.query_params))
@router.get("/api/live-monitor/daily-reports")
async def reports(request: Request): read(request); return await LiveMonitorClient().request("GET","/live-monitor/daily-reports",request,params=dict(request.query_params))
