from datetime import date, datetime
from uuid import uuid4
from sqlalchemy import Date, DateTime, Numeric, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.infrastructure.postgres.base import Base
class LiveEquityCurveModel(Base):
    __tablename__="live_equity_curve"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); strategy_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True,index=True); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str|None]=mapped_column(String(64),nullable=True); ts:Mapped[datetime]=mapped_column(DateTime(timezone=True)); total_equity:Mapped[float]=mapped_column(Numeric(32,8)); available_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); margin_used:Mapped[float|None]=mapped_column(Numeric(32,8)); unrealized_pnl:Mapped[float|None]=mapped_column(Numeric(32,8)); realized_pnl:Mapped[float|None]=mapped_column(Numeric(32,8)); drawdown_pct:Mapped[float|None]=mapped_column(Numeric(18,8)); source_event:Mapped[str|None]=mapped_column(String(128)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class LiveAccountDailySummaryModel(Base):
    __tablename__="live_account_daily_summary"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); trade_date:Mapped[date]=mapped_column(Date,index=True); exchange:Mapped[str]=mapped_column(String(32)); starting_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); ending_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); daily_return:Mapped[float|None]=mapped_column(Numeric(18,8)); max_drawdown:Mapped[float|None]=mapped_column(Numeric(18,8)); order_count:Mapped[int]=mapped_column(default=0); filled_order_count:Mapped[int]=mapped_column(default=0); failed_order_count:Mapped[int]=mapped_column(default=0); unknown_order_count:Mapped[int]=mapped_column(default=0); trade_count:Mapped[int]=mapped_column(default=0); fee_total:Mapped[float]=mapped_column(Numeric(32,8),default=0); circuit_breaker_count:Mapped[int]=mapped_column(default=0); emergency_stop_count:Mapped[int]=mapped_column(default=0); summary_json:Mapped[dict|None]=mapped_column(JSONB); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class LiveStrategyDailySummaryModel(LiveAccountDailySummaryModel):
    __tablename__="live_strategy_daily_summary"; __mapper_args__={"concrete":True}; strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); win_rate:Mapped[float|None]=mapped_column(Numeric(18,8)); profit_factor:Mapped[float|None]=mapped_column(Numeric(18,8)); cost_to_profit_ratio:Mapped[float|None]=mapped_column(Numeric(18,8))
class LiveRiskDailySummaryModel(Base):
    __tablename__="live_risk_daily_summary"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); trade_date:Mapped[date]=mapped_column(Date); circuit_breaker_count:Mapped[int]=mapped_column(default=0); order_unknown_count:Mapped[int]=mapped_column(default=0); order_failed_count:Mapped[int]=mapped_column(default=0); emergency_stop_count:Mapped[int]=mapped_column(default=0); detail_json:Mapped[dict|None]=mapped_column(JSONB); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class LiveObservationModel(Base):
    __tablename__="live_observation"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); symbols:Mapped[list]=mapped_column(JSONB); start_time:Mapped[datetime]=mapped_column(DateTime(timezone=True)); end_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); observation_type:Mapped[str]=mapped_column(String(64)); min_observation_days:Mapped[int]=mapped_column(default=7); status:Mapped[str]=mapped_column(String(64),index=True); latest_admission_result_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_by:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class LiveAdmissionResultModel(Base):
    __tablename__="live_admission_result"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); live_observation_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); decision:Mapped[str]=mapped_column(String(64),index=True); passed:Mapped[bool]=mapped_column(default=False); score:Mapped[float|None]=mapped_column(Numeric(8,2)); observation_days:Mapped[int]=mapped_column(); live_trade_count:Mapped[int]=mapped_column(); total_return:Mapped[float|None]=mapped_column(Numeric(18,8)); max_drawdown:Mapped[float|None]=mapped_column(Numeric(18,8)); win_rate:Mapped[float|None]=mapped_column(Numeric(18,8)); profit_factor:Mapped[float|None]=mapped_column(Numeric(18,8)); order_unknown_count:Mapped[int|None]=mapped_column(); order_failed_count:Mapped[int|None]=mapped_column(); circuit_breaker_count:Mapped[int|None]=mapped_column(); emergency_stop_count:Mapped[int|None]=mapped_column(); paper_live_return_deviation:Mapped[float|None]=mapped_column(Numeric(18,8)); paper_live_drawdown_deviation:Mapped[float|None]=mapped_column(Numeric(18,8)); warnings:Mapped[list|None]=mapped_column(JSONB); suggestions:Mapped[list|None]=mapped_column(JSONB); approval_required:Mapped[bool]=mapped_column(default=True); approval_status:Mapped[str|None]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class LiveDailyReportModel(Base):
    __tablename__="live_daily_report"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True,index=True); report_date:Mapped[date]=mapped_column(Date,index=True); report_type:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(64)); report_json:Mapped[dict|None]=mapped_column(JSONB); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
