from enum import StrEnum

class BacktestStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    DATA_LOADING = "DATA_LOADING"
    DATA_VALIDATING = "DATA_VALIDATING"
    RUNNING = "RUNNING"
    CALCULATING_METRICS = "CALCULATING_METRICS"
    BUILDING_REPLAY = "BUILDING_REPLAY"
    BUILDING_REPORT = "BUILDING_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
