from enum import StrEnum


class ApprovalType(StrEnum):
    SMALL_LIVE_APPLICATION = "SMALL_LIVE_APPLICATION"
    SCALE_UP_APPLICATION = "SCALE_UP_APPLICATION"
    ROLLBACK_APPROVAL = "ROLLBACK_APPROVAL"
    STRATEGY_PAUSE_APPROVAL = "STRATEGY_PAUSE_APPROVAL"
    STRATEGY_RETIRE_APPROVAL = "STRATEGY_RETIRE_APPROVAL"
    LIVE_RESTORE_APPROVAL = "LIVE_RESTORE_APPROVAL"
