from enum import StrEnum


class EvidenceType(StrEnum):
    BACKTEST_REPORT = "BACKTEST_REPORT"
    REPLAY_RECORD = "REPLAY_RECORD"
    AI_ANALYSIS_REPORT = "AI_ANALYSIS_REPORT"
    STRATEGY_SCORE = "STRATEGY_SCORE"
    SCORE_ADMISSION_RESULT = "SCORE_ADMISSION_RESULT"
    PAPER_TRADING_SUMMARY = "PAPER_TRADING_SUMMARY"
    SIMULATION_ADMISSION_RESULT = "SIMULATION_ADMISSION_RESULT"
    LIVE_TRADING_SUMMARY = "LIVE_TRADING_SUMMARY"
    LIVE_ADMISSION_RESULT = "LIVE_ADMISSION_RESULT"
    RISK_EVENT_SUMMARY = "RISK_EVENT_SUMMARY"
    ALERT_SUMMARY = "ALERT_SUMMARY"
    AUDIT_TRACE = "AUDIT_TRACE"
    APPROVAL_RECORD = "APPROVAL_RECORD"
