from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_paper_trading_schema"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
 op.create_table("paper_account", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("name",sa.String(128),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("currency",sa.String(32),nullable=False,server_default="USDT"), sa.Column("initial_balance",sa.Numeric(32,8),nullable=False), sa.Column("available_balance",sa.Numeric(32,8),nullable=False), sa.Column("margin_used",sa.Numeric(32,8),nullable=False,server_default="0"), sa.Column("unrealized_pnl",sa.Numeric(32,8),nullable=False,server_default="0"), sa.Column("realized_pnl",sa.Numeric(32,8),nullable=False,server_default="0"), sa.Column("equity",sa.Numeric(32,8),nullable=False), sa.Column("status",sa.String(64),nullable=False), sa.Column("created_by",postgresql.UUID(as_uuid=True)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index("idx_paper_account_status","paper_account",["status"]); op.create_index("idx_paper_account_exchange","paper_account",["exchange"])
 op.create_table("paper_position", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("account_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("paper_account.id"),nullable=False), sa.Column("strategy_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("internal_symbol",sa.String(64),nullable=False), sa.Column("position_side",sa.String(16),nullable=False), sa.Column("quantity",sa.Numeric(32,16),nullable=False), sa.Column("entry_price",sa.Numeric(32,16),nullable=False), sa.Column("mark_price",sa.Numeric(32,16)), sa.Column("leverage",sa.Numeric(8,2),nullable=False), sa.Column("margin",sa.Numeric(32,8),nullable=False), sa.Column("unrealized_pnl",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("realized_pnl",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("liquidation_price_estimate",sa.Numeric(32,16)), sa.Column("status",sa.String(64),nullable=False), sa.Column("opened_at",sa.DateTime(timezone=True)), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("paper_order", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("account_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("paper_account.id"),nullable=False), sa.Column("signal_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("risk_decision_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("internal_symbol",sa.String(64),nullable=False), sa.Column("side",sa.String(16),nullable=False), sa.Column("position_side",sa.String(16),nullable=False), sa.Column("action",sa.String(32),nullable=False), sa.Column("order_type",sa.String(32),nullable=False), sa.Column("requested_price",sa.Numeric(32,16)), sa.Column("limit_price",sa.Numeric(32,16)), sa.Column("fill_price",sa.Numeric(32,16)), sa.Column("quantity",sa.Numeric(32,16),nullable=False), sa.Column("leverage",sa.Numeric(8,2),nullable=False), sa.Column("status",sa.String(64),nullable=False), sa.Column("reason",sa.Text()), sa.Column("idempotency_key",sa.String(256),nullable=False,unique=True), sa.Column("trace_id",sa.String(128)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("filled_at",sa.DateTime(timezone=True)))
 op.create_table("paper_trade", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("account_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("paper_account.id"),nullable=False), sa.Column("paper_order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("paper_order.id"),nullable=False), sa.Column("signal_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("risk_decision_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True),nullable=False), sa.Column("exchange",sa.String(32),nullable=False), sa.Column("internal_symbol",sa.String(64),nullable=False), sa.Column("side",sa.String(16),nullable=False), sa.Column("position_side",sa.String(16),nullable=False), sa.Column("action",sa.String(32),nullable=False), sa.Column("fill_price",sa.Numeric(32,16),nullable=False), sa.Column("quantity",sa.Numeric(32,16),nullable=False), sa.Column("notional_value",sa.Numeric(32,8),nullable=False), sa.Column("leverage",sa.Numeric(8,2),nullable=False), sa.Column("fee",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("slippage",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("funding_fee",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("realized_pnl",sa.Numeric(32,8),server_default="0",nullable=False), sa.Column("equity_after",sa.Numeric(32,8),nullable=False), sa.Column("trace_id",sa.String(128)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("paper_balance_ledger", sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("uuid_generate_v4()")), sa.Column("account_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("paper_account.id"),nullable=False), sa.Column("strategy_id",postgresql.UUID(as_uuid=True)), sa.Column("strategy_version_id",postgresql.UUID(as_uuid=True)), sa.Column("related_order_id",postgresql.UUID(as_uuid=True)), sa.Column("related_trade_id",postgresql.UUID(as_uuid=True)), sa.Column("ledger_type",sa.String(64),nullable=False), sa.Column("amount",sa.Numeric(32,8),nullable=False), sa.Column("balance_before",sa.Numeric(32,8),nullable=False), sa.Column("balance_after",sa.Numeric(32,8),nullable=False), sa.Column("description",sa.Text()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
def downgrade():
 op.drop_table("paper_balance_ledger"); op.drop_table("paper_trade"); op.drop_table("paper_order"); op.drop_table("paper_position"); op.drop_table("paper_account")
