from datetime import datetime
from uuid import uuid4
from sqlalchemy import DateTime, Numeric, String, Text, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.infrastructure.postgres.base import Base
class PaperAccountModel(Base):
    __tablename__="paper_account"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); name:Mapped[str]=mapped_column(String(128)); exchange:Mapped[str]=mapped_column(String(32),index=True); currency:Mapped[str]=mapped_column(String(32),default="USDT"); initial_balance:Mapped[float]=mapped_column(Numeric(32,8)); available_balance:Mapped[float]=mapped_column(Numeric(32,8)); margin_used:Mapped[float]=mapped_column(Numeric(32,8),default=0); unrealized_pnl:Mapped[float]=mapped_column(Numeric(32,8),default=0); realized_pnl:Mapped[float]=mapped_column(Numeric(32,8),default=0); equity:Mapped[float]=mapped_column(Numeric(32,8)); status:Mapped[str]=mapped_column(String(64),index=True); created_by:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class PaperPositionModel(Base):
    __tablename__="paper_position"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),ForeignKey("paper_account.id"),index=True); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str]=mapped_column(String(64),index=True); position_side:Mapped[str]=mapped_column(String(16)); quantity:Mapped[float]=mapped_column(Numeric(32,16)); entry_price:Mapped[float]=mapped_column(Numeric(32,16)); mark_price:Mapped[float|None]=mapped_column(Numeric(32,16),nullable=True); leverage:Mapped[float]=mapped_column(Numeric(8,2)); margin:Mapped[float]=mapped_column(Numeric(32,8)); unrealized_pnl:Mapped[float]=mapped_column(Numeric(32,8),default=0); realized_pnl:Mapped[float]=mapped_column(Numeric(32,8),default=0); liquidation_price_estimate:Mapped[float|None]=mapped_column(Numeric(32,16),nullable=True); status:Mapped[str]=mapped_column(String(64),index=True); opened_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class PaperOrderModel(Base):
    __tablename__="paper_order"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),ForeignKey("paper_account.id"),index=True); signal_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); risk_decision_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str]=mapped_column(String(64)); side:Mapped[str]=mapped_column(String(16)); position_side:Mapped[str]=mapped_column(String(16)); action:Mapped[str]=mapped_column(String(32)); order_type:Mapped[str]=mapped_column(String(32)); requested_price:Mapped[float|None]=mapped_column(Numeric(32,16),nullable=True); limit_price:Mapped[float|None]=mapped_column(Numeric(32,16),nullable=True); fill_price:Mapped[float|None]=mapped_column(Numeric(32,16),nullable=True); quantity:Mapped[float]=mapped_column(Numeric(32,16)); leverage:Mapped[float]=mapped_column(Numeric(8,2)); status:Mapped[str]=mapped_column(String(64),index=True); reason:Mapped[str|None]=mapped_column(Text,nullable=True); idempotency_key:Mapped[str]=mapped_column(String(256),unique=True); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); filled_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class PaperTradeModel(Base):
    __tablename__="paper_trade"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),ForeignKey("paper_account.id"),index=True); paper_order_id:Mapped[str]=mapped_column(UUID(as_uuid=False),ForeignKey("paper_order.id"),index=True); signal_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); risk_decision_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); strategy_version_id:Mapped[str]=mapped_column(UUID(as_uuid=False)); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str]=mapped_column(String(64)); side:Mapped[str]=mapped_column(String(16)); position_side:Mapped[str]=mapped_column(String(16)); action:Mapped[str]=mapped_column(String(32)); fill_price:Mapped[float]=mapped_column(Numeric(32,16)); quantity:Mapped[float]=mapped_column(Numeric(32,16)); notional_value:Mapped[float]=mapped_column(Numeric(32,8)); leverage:Mapped[float]=mapped_column(Numeric(8,2)); fee:Mapped[float]=mapped_column(Numeric(32,8),default=0); slippage:Mapped[float]=mapped_column(Numeric(32,8),default=0); funding_fee:Mapped[float]=mapped_column(Numeric(32,8),default=0); realized_pnl:Mapped[float]=mapped_column(Numeric(32,8),default=0); equity_after:Mapped[float]=mapped_column(Numeric(32,8)); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
class PaperBalanceLedgerModel(Base):
    __tablename__="paper_balance_ledger"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),ForeignKey("paper_account.id"),index=True); strategy_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); strategy_version_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); related_order_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); related_trade_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); ledger_type:Mapped[str]=mapped_column(String(64),index=True); amount:Mapped[float]=mapped_column(Numeric(32,8)); balance_before:Mapped[float]=mapped_column(Numeric(32,8)); balance_after:Mapped[float]=mapped_column(Numeric(32,8)); description:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
