from enum import StrEnum
class LiveAdmissionDecision(StrEnum):
    CONTINUE_SMALL_LIVE = "CONTINUE_SMALL_LIVE"
    EXTEND_OBSERVATION = "EXTEND_OBSERVATION"
    ROLLBACK_TO_PAPER = "ROLLBACK_TO_PAPER"
    PAUSE_STRATEGY = "PAUSE_STRATEGY"
    ALLOW_SCALE_UP_APPLICATION = "ALLOW_SCALE_UP_APPLICATION"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
