from enum import StrEnum
class ReportType(StrEnum):
    BACKTEST_REPORT = "BACKTEST_REPORT"
    DRAWDOWN_REPORT = "DRAWDOWN_REPORT"
    AI_ANALYSIS_REPORT = "AI_ANALYSIS_REPORT"
    STRATEGY_SCORE_REPORT = "STRATEGY_SCORE_REPORT"
