from enum import StrEnum

class StrategyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    PUBLISHED = "PUBLISHED"
    DRAFT = "DRAFT"
    READY_FOR_BACKTEST = "READY_FOR_BACKTEST"
    BACKTESTING = "BACKTESTING"
    BACKTEST_FAILED = "BACKTEST_FAILED"
    BACKTEST_PASSED = "BACKTEST_PASSED"
    AI_REVIEWING = "AI_REVIEWING"
    READY_FOR_SIMULATION = "READY_FOR_SIMULATION"
    SIMULATION_RUNNING = "SIMULATION_RUNNING"
    SIMULATION_PASSED = "SIMULATION_PASSED"
    SMALL_LIVE = "SMALL_LIVE"
    LIVE = "LIVE"
    PAUSED = "PAUSED"
    RETIRED = "RETIRED"
