from datetime import datetime
from uuid import uuid4
from sqlalchemy import Boolean, DateTime, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.infrastructure.postgres.base import Base
class ExchangeAccountModel(Base):
    __tablename__="exchange_account"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); name:Mapped[str]=mapped_column(String(128)); exchange:Mapped[str]=mapped_column(String(32),index=True); account_type:Mapped[str]=mapped_column(String(64)); environment:Mapped[str]=mapped_column(String(32)); status:Mapped[str]=mapped_column(String(64),index=True); trading_enabled:Mapped[bool]=mapped_column(Boolean,default=False,index=True); read_enabled:Mapped[bool]=mapped_column(Boolean,default=True); default_currency:Mapped[str]=mapped_column(String(32),default="USDT"); default_margin_mode:Mapped[str|None]=mapped_column(String(64),nullable=True); default_position_mode:Mapped[str|None]=mapped_column(String(64),nullable=True); expected_outbound_ip:Mapped[str|None]=mapped_column(String(64),nullable=True); ip_whitelist_status:Mapped[str|None]=mapped_column(String(64),nullable=True); last_connectivity_check_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); last_connectivity_status:Mapped[str|None]=mapped_column(String(64),nullable=True); last_connectivity_error:Mapped[str|None]=mapped_column(Text,nullable=True); created_by:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class ExchangeAPICredentialModel(Base):
    __tablename__="exchange_api_credential"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); api_key_masked:Mapped[str]=mapped_column(String(128)); api_key_hash:Mapped[str]=mapped_column(String(128),unique=True); encrypted_api_key:Mapped[str]=mapped_column(Text); encrypted_secret_key:Mapped[str]=mapped_column(Text); encrypted_passphrase:Mapped[str|None]=mapped_column(Text,nullable=True); encrypted_data_key:Mapped[str|None]=mapped_column(Text,nullable=True); key_provider:Mapped[str]=mapped_column(String(64)); key_id:Mapped[str|None]=mapped_column(String(128),nullable=True); algorithm:Mapped[str]=mapped_column(String(64)); permission_scopes:Mapped[list]=mapped_column(JSONB); has_read_permission:Mapped[bool]=mapped_column(Boolean,default=False); has_trade_permission:Mapped[bool]=mapped_column(Boolean,default=False); has_withdraw_permission:Mapped[bool]=mapped_column(Boolean,default=False); status:Mapped[str]=mapped_column(String(64),index=True); last_verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); last_verify_error:Mapped[str|None]=mapped_column(Text,nullable=True); created_by:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class AccountStateSnapshotModel(Base):
    __tablename__="account_state_snapshot"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); currency:Mapped[str]=mapped_column(String(32)); total_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); available_equity:Mapped[float|None]=mapped_column(Numeric(32,8)); margin_used:Mapped[float|None]=mapped_column(Numeric(32,8)); unrealized_pnl:Mapped[float|None]=mapped_column(Numeric(32,8)); raw_json:Mapped[dict|None]=mapped_column(JSONB); event_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); synced_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); freshness_status:Mapped[str]=mapped_column(String(64),default="UNKNOWN")
class PositionStateSnapshotModel(Base):
    __tablename__="position_state_snapshot"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str]=mapped_column(String(64),index=True); exchange_symbol:Mapped[str]=mapped_column(String(64)); position_side:Mapped[str]=mapped_column(String(32)); quantity:Mapped[float]=mapped_column(Numeric(32,16)); entry_price:Mapped[float|None]=mapped_column(Numeric(32,16)); mark_price:Mapped[float|None]=mapped_column(Numeric(32,16)); leverage:Mapped[float|None]=mapped_column(Numeric(8,2)); status:Mapped[str]=mapped_column(String(64),index=True); raw_json:Mapped[dict|None]=mapped_column(JSONB); event_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); synced_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); freshness_status:Mapped[str]=mapped_column(String(64),default="UNKNOWN")
class OrderStateSnapshotModel(Base):
    __tablename__="order_state_snapshot"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); exchange:Mapped[str]=mapped_column(String(32)); internal_symbol:Mapped[str]=mapped_column(String(64)); exchange_symbol:Mapped[str]=mapped_column(String(64)); exchange_order_id:Mapped[str|None]=mapped_column(String(128),nullable=True); client_order_id:Mapped[str|None]=mapped_column(String(128),nullable=True); order_state:Mapped[str|None]=mapped_column(String(64),index=True); raw_json:Mapped[dict|None]=mapped_column(JSONB); synced_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class CredentialAuditLogModel(Base):
    __tablename__="credential_audit_log"; id:Mapped[str]=mapped_column(UUID(as_uuid=False),primary_key=True,default=lambda:str(uuid4())); account_id:Mapped[str]=mapped_column(UUID(as_uuid=False),index=True); credential_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); action:Mapped[str]=mapped_column(String(128)); operator_id:Mapped[str|None]=mapped_column(UUID(as_uuid=False),nullable=True); result:Mapped[str]=mapped_column(String(64)); message:Mapped[str|None]=mapped_column(Text,nullable=True); trace_id:Mapped[str|None]=mapped_column(String(128),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
