from enum import StrEnum
class AITaskStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    LOADING_DATA = "LOADING_DATA"
    RUNNING = "RUNNING"
    VALIDATING_OUTPUT = "VALIDATING_OUTPUT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
